#!/bin/bash
set -e
DEVICE="$1"
SHA=$(sha256sum preload.so | cut -d' ' -f1)
SHA_SHORT=$(echo "$SHA" | cut -c1-16)

mkdir -p _site
cp preload.so "_site/preload-${DEVICE}.so"
cp target.h "_site/target-${DEVICE}.h"

OUT="_site/index.html"

# 用 printf 逐行写 HTML，无 heredoc，无转义问题
printf '%s\n' '<!DOCTYPE html>' > "$OUT"
printf '%s\n' '<html lang="zh-CN">' >> "$OUT"
printf '%s\n' '<head>' >> "$OUT"
printf '%s\n' '<meta charset="UTF-8">' >> "$OUT"
printf '%s\n' '<meta name="viewport" content="width=device-width, initial-scale=1.0">' >> "$OUT"
printf '%s\n' "<title>${DEVICE} | GhostLock KernelSU</title>" >> "$OUT"
printf '%s\n' '<style>' >> "$OUT"
printf '%s\n' '*{margin:0;padding:0;box-sizing:border-box}' >> "$OUT"
printf '%s\n' 'body{background:#0a0a0f;color:#e8e8f0;font-family:system-ui,-apple-system,sans-serif;min-height:100vh;padding:40px 20px}' >> "$OUT"
printf '%s\n' '.container{max-width:680px;margin:0 auto}' >> "$OUT"
printf '%s\n' 'header{text-align:center;margin-bottom:36px}' >> "$OUT"
printf '%s\n' 'h1{font-size:2rem;background:linear-gradient(90deg,#667eea,#764ba2);-webkit-background-clip:text;-webkit-text-fill-color:transparent}' >> "$OUT"
printf '%s\n' '.subtitle{color:#6b7280;font-size:.9rem;margin-top:6px}' >> "$OUT"
printf '%s\n' '.card{background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.06);border-radius:14px;padding:24px;margin-bottom:16px}' >> "$OUT"
printf '%s\n' '.card h2{font-size:1.05rem;color:#fff;margin-bottom:12px}' >> "$OUT"
printf '%s\n' '.code-block{background:#11131a;border:1px solid rgba(255,255,255,.08);border-radius:8px;padding:14px;font-family:monospace;font-size:.8rem;color:#a5b4fc;overflow-x:auto;position:relative}' >> "$OUT"
printf '%s\n' '.code-block pre{margin:0;white-space:pre-wrap}' >> "$OUT"
printf '%s\n' '.copy-btn{position:absolute;top:8px;right:8px;background:rgba(255,255,255,.08);border:none;color:#a5b4fc;padding:3px 8px;border-radius:4px;font-size:.7rem;cursor:pointer}' >> "$OUT"
printf '%s\n' '.btn{display:block;width:100%;text-align:center;background:linear-gradient(135deg,#667eea,#764ba2);color:#fff;text-decoration:none;padding:12px;border-radius:8px;font-weight:600;margin-bottom:8px;font-size:.9rem}' >> "$OUT"
printf '%s\n' '.btn-secondary{background:linear-gradient(135deg,#11998e,#38ef7d)}' >> "$OUT"
printf '%s\n' '.btn-danger{background:linear-gradient(135deg,#eb3349,#f45c43)}' >> "$OUT"
printf '%s\n' '.info{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:12px;font-size:.8rem}' >> "$OUT"
printf '%s\n' '.info-item{background:rgba(255,255,255,.02);padding:8px 12px;border-radius:6px}' >> "$OUT"
printf '%s\n' '.info-item span{display:block;color:#6b7280;font-size:.65rem;text-transform:uppercase;margin-bottom:2px}' >> "$OUT"
printf '%s\n' '.info-item code{color:#a5b4fc;font-family:monospace}' >> "$OUT"
printf '%s\n' '.warning{background:rgba(245,158,11,.08);border-left:3px solid #f59e0b;padding:12px;border-radius:0 8px 8px 0;margin-top:16px;font-size:.8rem;color:#d4d4d8}' >> "$OUT"
printf '%s\n' '.warning strong{color:#fbbf24}' >> "$OUT"
printf '%s\n' 'footer{text-align:center;margin-top:32px;color:#4b5563;font-size:.7rem}' >> "$OUT"
printf '%s\n' '</style>' >> "$OUT"
printf '%s\n' '</head>' >> "$OUT"
printf '%s\n' '<body>' >> "$OUT"
printf '%s\n' '<div class="container">' >> "$OUT"
printf '%s\n' '<header>' >> "$OUT"
printf '%s\n' "<h1>🔓 ${DEVICE}</h1>" >> "$OUT"
printf '%s\n' '<p class="subtitle">GhostLock + KernelSU late-load</p>' >> "$OUT"
printf '%s\n' '</header>' >> "$OUT"

printf '%s\n' '<div class="card">' >> "$OUT"
printf '%s\n' '<h2>📱 设备信息</h2>' >> "$OUT"
printf '%s\n' '<div class="info">' >> "$OUT"
printf '%s\n' "<div class=\"info-item\"><span>设备代号</span><code>${DEVICE}</code></div>" >> "$OUT"
printf '%s\n' '<div class="info-item"><span>Payload</span><code>preload.so</code></div>' >> "$OUT"
printf '%s\n' '<div class="info-item"><span>模式</span><code>KernelSU late-load</code></div>' >> "$OUT"
printf '%s\n' "<div class=\"info-item\"><span>SHA256</span><code>${SHA_SHORT}...</code></div>" >> "$OUT"
printf '%s\n' '</div>' >> "$OUT"
printf '%s\n' '</div>' >> "$OUT"

printf '%s\n' '<div class="card">' >> "$OUT"
printf '%s\n' '<h2>⚡ 一键越狱</h2>' >> "$OUT"
printf '%s\n' '<div class="code-block"><button class="copy-btn" onclick="copy(this)">复制</button>' >> "$OUT"
printf '%s\n' '<pre>' >> "$OUT"
printf '%s\n' "adb push preload-${DEVICE}.so /data/local/tmp/preload.so" >> "$OUT"
printf '%s\n' "adb shell 'chmod 755 /data/local/tmp/preload.so'" >> "$OUT"
printf '%s\n' "adb shell 'LD_PRELOAD=/data/local/tmp/preload.so /system/bin/toybox id'" >> "$OUT"
printf '%s\n' '</pre></div>' >> "$OUT"
printf '%s\n' "<a class=\"btn\" href=\"preload-${DEVICE}.so\" download>⬇️ 下载 preload.so</a>" >> "$OUT"
printf '%s\n' '<a class="btn btn-secondary" href="https://github.com/tiann/KernelSU/releases" target="_blank">📥 下载 KernelSU 管理器</a>' >> "$OUT"
printf '%s\n' '</div>' >> "$OUT"

printf '%s\n' '<div class="card">' >> "$OUT"
printf '%s\n' '<h2>📋 使用步骤</h2>' >> "$OUT"
printf '%s\n' '<ol style="margin:0;padding-left:18px;color:#b0b3c7;font-size:.85rem">' >> "$OUT"
printf '%s\n' '<li style="margin-bottom:8px"><strong style="color:#e8e8f0">安装 KernelSU 管理器 APK</strong>（无需提前 root）</li>' >> "$OUT"
printf '%s\n' '<li style="margin-bottom:8px"><strong style="color:#e8e8f0">开启 USB 调试</strong>，连接电脑</li>' >> "$OUT"
printf '%s\n' '<li style="margin-bottom:8px"><strong style="color:#e8e8f0">执行上方 adb 命令</strong>，等待利用完成</li>' >> "$OUT"
printf '%s\n' '<li style="margin-bottom:8px"><strong style="color:#e8e8f0">打开 KernelSU 管理器</strong>，授予 root 权限</li>' >> "$OUT"
printf '%s\n' '<li><strong style="color:#e8e8f0">享受 root 环境</strong>（无需解锁 Bootloader）</li>' >> "$OUT"
printf '%s\n' '</ol>' >> "$OUT"
printf '%s\n' '<div class="warning"><strong>⚠️ 风险提示</strong><br>利用失败会导致 kernel panic → 自动重启。偏移由自动化脚本提取，可能存在误差。仅供安全研究。</div>' >> "$OUT"
printf '%s\n' '</div>' >> "$OUT"

printf '%s\n' '<div class="card">' >> "$OUT"
printf '%s\n' '<h2>🔧 高级选项</h2>' >> "$OUT"
printf '%s\n' '<div class="code-block"><button class="copy-btn" onclick="copy(this)">复制</button>' >> "$OUT"
printf '%s\n' '<pre>' >> "$OUT"
printf '%s\n' '# 自定义包名' >> "$OUT"
printf '%s\n' "adb shell 'KSUD_PACKAGE=com.example.manager LD_PRELOAD=/data/local/tmp/preload.so /system/bin/toybox id'" >> "$OUT"
printf '%s\n' '' >> "$OUT"
printf '%s\n' '# 跳过 ksud 写出' >> "$OUT"
printf '%s\n' "adb shell 'KSUD_SKIP_WRITE=1 LD_PRELOAD=/data/local/tmp/preload.so /system/bin/toybox id'" >> "$OUT"
printf '%s\n' '' >> "$OUT"
printf '%s\n' '# 查看日志' >> "$OUT"
printf '%s\n' "adb shell 'cat /data/local/tmp/ksud.log /data/local/tmp/ksud.preload.log'" >> "$OUT"
printf '%s\n' '</pre></div>' >> "$OUT"
printf '%s\n' "<a class=\"btn btn-danger\" href=\"target-${DEVICE}.h\" download>⬇️ 下载 target.h（调试用）</a>" >> "$OUT"
printf '%s\n' '</div>' >> "$OUT"

printf '%s\n' '<footer>' >> "$OUT"
printf '%s\n' '<p>基于 <a href="https://github.com/woshimaniubi8/CVE-2026-43499-root-KernelSU" style="color:#667eea">CVE-2026-43499-root-KernelSU</a></p>' >> "$OUT"
printf '%s\n' '<p>仅供安全研究与学习用途</p>' >> "$OUT"
printf '%s\n' '</footer>' >> "$OUT"

printf '%s\n' '</div>' >> "$OUT"
printf '%s\n' '<script>' >> "$OUT"
printf '%s\n' 'function copy(btn){var pre=btn.parentElement.querySelector("pre");navigator.clipboard.writeText(pre.innerText).then(function(){btn.textContent="已复制";setTimeout(function(){btn.textContent="复制"},1500)});}' >> "$OUT"
printf '%s\n' '</script>' >> "$OUT"
printf '%s\n' '</body>' >> "$OUT"
printf '%s\n' '</html>' >> "$OUT"

echo "Generated _site/index.html"
